export const DAYS = {
  push: {
    label: "Senin",
    name: "Push Day",
    focus: "Chest + Triceps",
    color: "push",
    kcal: 390,
    exercises: [
      {
        id: "chest_press",
        name: "Machine Chest Press",
        target: "4 × 10",
        sets: 4,
        reps: 10,
        suggestedWeight: "15–20",
      },
      {
        id: "chest_fly",
        name: "Chest Fly",
        target: "3 × 12",
        sets: 3,
        reps: 12,
        suggestedWeight: "10–15",
      },
      {
        id: "dips",
        name: "Assisted Dips",
        target: "3 × 10",
        sets: 3,
        reps: 10,
        suggestedWeight: "—",
      },
    ],
    cardio: {
      icon: "🏃",
      name: "Treadmill Incline",
      desc: "Speed 5–6 km/h · Incline 7–10 · 12–15 menit",
    },
  },
  legs: {
    label: "Selasa",
    name: "Legs Day",
    focus: "Big Fat Burner",
    color: "legs",
    kcal: 430,
    exercises: [
      {
        id: "leg_press",
        name: "Leg Press",
        target: "4 × 12",
        sets: 4,
        reps: 12,
        suggestedWeight: "50–70",
      },
      {
        id: "leg_ext",
        name: "Leg Extension",
        target: "3 × 12",
        sets: 3,
        reps: 12,
        suggestedWeight: "20–25",
      },
      {
        id: "leg_curl",
        name: "Lying Leg Curl",
        target: "3 × 12",
        sets: 3,
        reps: 12,
        suggestedWeight: "20–25",
      },
      {
        id: "squat",
        name: "Bodyweight Squat",
        target: "3 × 15",
        sets: 3,
        reps: 15,
        suggestedWeight: "BW",
      },
    ],
    cardio: { icon: "🏃", name: "Treadmill", desc: "10–12 menit" },
  },
  pull: {
    label: "Kamis",
    name: "Pull Day",
    focus: "Back + Biceps",
    color: "pull",
    kcal: 380,
    exercises: [
      {
        id: "lat_pull",
        name: "Wide Lat Pulldown",
        target: "4 × 10",
        sets: 4,
        reps: 10,
        suggestedWeight: "20–25",
      },
      {
        id: "seated_row",
        name: "Seated Row",
        target: "3 × 10",
        sets: 3,
        reps: 10,
        suggestedWeight: "20–25",
      },
      {
        id: "chinup",
        name: "Assisted Chin-up",
        target: "3 × 8–10",
        sets: 3,
        reps: 10,
        suggestedWeight: "—",
      },
      {
        id: "preacher",
        name: "Preacher Curl",
        target: "3 × 12",
        sets: 3,
        reps: 12,
        suggestedWeight: "7–10",
      },
    ],
    cardio: { icon: "🚴", name: "Elliptical / Treadmill", desc: "10–12 menit" },
  },
  core: {
    label: "Jumat",
    name: "Core + Fat Burn",
    focus: "Abs + Cardio",
    color: "core",
    kcal: 370,
    exercises: [
      {
        id: "cable_crunch",
        name: "Cable Crunch",
        target: "4 × 15",
        sets: 4,
        reps: 15,
        suggestedWeight: "10–15",
      },
      {
        id: "plank",
        name: "Plank",
        target: "3 × 30–40 detik",
        sets: 3,
        reps: null,
        suggestedWeight: "BW",
      },
      {
        id: "flutter",
        name: "Flutter Kick",
        target: "3 × 20",
        sets: 3,
        reps: 20,
        suggestedWeight: "BW",
      },
    ],
    cardio: { icon: "🚣", name: "Rowing Machine", desc: "12–15 menit" },
  },
};
